version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 2s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend 
    ports:
      - 8080:8080 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todo_app
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - 80:8080
    environment:
      - BACKEND_URL=http://localhost:8080